server:
  port: 28888

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth
            uri: lb://yuyu-auth
            predicates:
              - Path=/auth/**
          - id: api
            uri: lb://yuyu-api
            predicates:
              - Path=/api/**
