services:
  yuyu:
    image: 192.168.18.124:80/xiaoxipeng/yuyu:0.0.1
    container_name: xiaoxipeng-yuyu
    restart: always
    ports:
      - "8080:8080"
    cap_add:
      - ALL
    depends_on:
      - mysql
      - redis
  auth:
    image: 192.168.18.124:80/xiaoxipeng/auth:0.0.1
    container_name: xiaoxipeng-auth
    restart: always
    ports:
      - "30000:30000"
    cap_add:
      - ALL
    depends_on:
      - mysql
      - redis
  gateway:
    image: 192.168.18.124:80/xiaoxipeng/gateway:0.0.1
    container_name: xiaoxipeng-gateway
    restart: always
    ports:
      - "38888:38888"
    cap_add:
      - ALL
    depends_on:
      - yuyu
      - auth
      - config
  config:
    image: 192.168.18.124:80/xiaoxipeng/config:0.0.1
    container_name: xiaoxipeng-config
    restart: always
    ports:
      - "10000:10000"
    cap_add:
      - ALL
  redis:
    image: 192.168.18.124:80/xiaoxipeng/redis:5
    container_name: xiaoxipeng-redis
    restart: always
    volumes:
      - /var/redis/:/data/redis/
      - type: bind
        source: ./common/config/redis/redis.conf
        target: /path/to/redis.conf
    entrypoint: ["redis-server", "/path/to/redis.conf"]
    ports:
      - "6379:6379"
    cap_add:
      - ALL
  mysql:
    image: 192.168.18.124:80/xiaoxipeng/mysql:8
    container_name: xiaoxipeng-mysql
    restart: always
    volumes:
      - /var/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    cap_add:
      - ALL
  nginx:
    image: 192.168.18.124:80/xiaoxipeng/nginx:1.27.4
    container_name: xiaoxipeng-nginx
    restart: always
    volumes:
      - /var/nginx/:/var/log/nginx/
      - /root/data/web/:/web/
      - type: bind
        source: ./common/config/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    cap_add:
      - ALL
    depends_on:
      - yuyu
  nacos:
    image: 192.168.18.124:80/xiaoxipeng/nacos:2.4.3
    container_name: xiaoxipeng-nacos
    restart: always
    volumes:
      - /var/nacos/:/home/nacos/
    environment:
      - MODE=true
      - MYSQL_SERVICE_USER=admin
      - MYSQL_SERVICE_PASSWORD=admin123
    ports:
      - "8848:8848"
      - "9848":"9848"
    cap_add:
      - ALL