services:
  yuyu:
    image: xiaoxipeng/yuyu:0.0.1
    container_name: xiaoxipeng-yuyu
    restart: always
    ports:
      - "8080:8080"
    cap_add:
      - ALL
    depends_on:
      - mysql
      - redis
    networks:
      - bridge
  redis:
    image: xiaoxipeng/redis:5
    container_name: xiaoxipeng-redis
    restart: always
    ports:
      - "6379:6379"
    cap_add:
      - ALL
    networks:
      - bridge
  mysql:
    image: xiaoxipeng/mysql:8
    container_name: xiaoxipeng-mysql
    restart: always
    ports:
      - "3306:3306"
    cap_add:
      - ALL
    networks:
      - bridge