services:
  api:
    image: 192.168.18.124:80/xiaoxipeng/yuyu-api:0.0.2
    container_name: xiaoxipeng-api
    restart: always
    ports:
      - "30010:30010"
    cap_add:
      - ALL
    depends_on:
      - gateway
  auth:
    image: 192.168.18.124:80/xiaoxipeng/yuyu-auth:0.0.2
    container_name: xiaoxipeng-auth
    restart: always
    ports:
      - "30000:30000"
    cap_add:
      - ALL
    depends_on:
      - gateway
  gateway:
    image: 192.168.18.124:80/xiaoxipeng/yuyu-gateway:0.0.2
    container_name: xiaoxipeng-gateway
    restart: always
    ports:
      - "38888:38888"
    cap_add:
      - ALL
    depends_on:
      - mysql
      - redis
      - nacos
  config:
    image: 192.168.18.124:80/xiaoxipeng/yuyu-config:0.0.2
    container_name: xiaoxipeng-config
    restart: always
    ports:
      - "10000:10000"
    cap_add:
      - ALL
    networks:
      default:
        ipv4_address: 172.20.1.1
  redis:
    image: 192.168.18.124:80/xiaoxipeng/redis:5
    container_name: xiaoxipeng-redis
    restart: always
    volumes:
      - /var/redis/:/data/redis/
      - type: bind
        source: ./common/config/redis/redis.conf
        target: /path/to/redis.conf
    entrypoint: ["redis-server", "/path/to/redis.conf"]
    ports:
      - "6379:6379"
    cap_add:
      - ALL
  mysql:
    image: 192.168.18.124:80/xiaoxipeng/mysql:8
    container_name: xiaoxipeng-mysql
    restart: always
    volumes:
      - /var/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    cap_add:
      - ALL
  nginx:
    image: 192.168.18.124:80/xiaoxipeng/nginx:1.27.4
    container_name: xiaoxipeng-nginx
    restart: always
    volumes:
      - /var/nginx/:/var/log/nginx/
      - /root/data/web/:/web/
      - type: bind
        source: ./common/config/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    cap_add:
      - ALL
  nacos:
    image: 192.168.18.124:80/xiaoxipeng/nacos:2.4.3
    container_name: xiaoxipeng-nacos
    restart: always
    volumes:
      # 包含nacos日志
      - /var/nacos/:/home/nacos/
    environment:
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    ports:
      - "8848:8848"
      - "9848:9848"
    cap_add:
      - ALL
    networks:
      default:
        ipv4_address: 172.20.1.0
networks:
  # docker-compose会根据的项目名称默认创建一个yuyu_default的网络
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1