server:
  port: 10000

spring:
  application:
    name: yuyu-config
  profiles:
    active:
      - native
  cloud:
    nacos:
      server-addr: ${NACOS_ADDRESS:localhost:8848}
    config:
      server:
        native:
          search-locations: file:./config-repo
          # 禁用label标签
          add-label-locations: false