server:
  port: 10000

spring:
  application:
    name: yuyu-config
  profiles:
    active:
      - native
  cloud:
    nacos:
      server-addr: ${NACOS_ADDRESS:172.20.1.0:8848}
    config:
      server:
        native:
          search-locations: file:./config-repo/{application}/
          # 禁用label标签
          add-label-locations: false

#logging:
#  level:
#    root: DEBUG