server:
  port: 10001

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_ADDRESS:localhost:3306}/yuyu?allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=false&characterEncoding=utf8
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1

decorator:
  datasource:
    p6spy:
      enable-logging: true
      # 日志格式
      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
      # 自定义日志类
      logging: custom
      custom-appender-class: com.xiaoxipeng.yuyu.aotuconfigure.config.PliuspyStdoutLogger
