server:
  port: 10010

spring:
  data:
    # redis config
    redis:
      host: ${REDIS_ADDRESS:127.0.0.1}
      port: 6379
      database: 1
  # mysql config
  datasource:
    url: jdbc:mysql://${MYSQL_ADDRESS:localhost:3306}/yuyu?allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=false&characterEncoding=utf8
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1


mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml

decorator:
  datasource:
    p6spy:
      enable-logging: true
      # 日志格式
      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
      # 自定义日志类
      logging: custom
      custom-appender-class: com.xiaoxipeng.yuyu.aotuconfigure.config.PliuspyStdoutLogger
