server:
  port: 28888

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth
            uri: lb://yuyu-auth
            predicates:
              - Path=/yuyu-auth/**
            filters:
              - StripPrefix=1
          - id: api
            uri: lb://yuyu-api
            predicates:
              - Path=/yuyu-api/**
            filters:
              - StripPrefix=1

