server:
  port: 38888

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth
            uri: lb://yuyu-auth
            predicates:
              - Path=/yuyu-auth/**
            filters:
              - StripPrefix=1
          - id: api
            uri: lb://yuyu-api
            predicates:
              - Path=/yuyu-api/**
            filters:
              - StripPrefix=1
          - id: anything
            uri: lb://yuyu-api
            predicates:
              - Path=/**
            filters:
              - StripPrefix=1

decorator:
  datasource:
    p6spy:
      enable-logging: false