server:
  port: 18888

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth
            uri: lb://yuyu-auth
            predicates:
              - Path=/yuyu-auth/**
            filters:
              - StripPrefix=1
          - id: api
            uri: lb://yuyu-api
            predicates:
              - Path=/yuyu-api/**
            filters:
              - StripPrefix=1
          - id: anything
            uri: lb://yuyu-api
            predicates:
              - Path=/**
            filters:
              - StripPrefix=1

decorator:
  datasource:
    p6spy:
      enable-logging: true
      # 日志格式
      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
      # 自定义日志类
      logging: custom
      custom-appender-class: com.xiaoxipeng.yuyu.aotuconfigure.config.PliuspyStdoutLogger
