spring:
  profiles:
    active: dev
  application:
    # 应用名称，用于在 Nacos 中查找配置
    name: yuyu-auth
  cloud:
    nacos:
      server-addr: ${NACOS_ADDRESS:172.20.0.3:8848}
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
  config:
    import: configserver:${CONFIG_SERVER_ADDRESS:http://172.20.0.2:10000}

logging:
  config: ${CONFIG_SERVER_ADDRESS:http://172.20.0.2:10000}/${spring.application.name}/${spring.profiles.active}/logback-spring.xml?useDefaultLabel=true&resolvePlaceholders=false

