spring:
  profiles:
    active: dev
  application:
    # 应用名称，用于在 Nacos 中查找配置
    name: yuyu-gateway
  cloud:
    nacos:
      server-addr: ${NACOS_ADDRESS:localhost:8848}
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      uri: ${CONFIG_SERVER_ADDRESS:http://localhost:10000}
  config:
    import: configserver:${CONFIG_SERVER_ADDRESS:http://localhost:10000}

