spring:
  profiles:
    active: dev
  application:
    # 应用名称，用于在 Nacos 中查找配置
    name: yuyu-gateway
  cloud:
    nacos:
      server-addr: ${NACOS_ADDRESS:172.20.1.0:8848}
  config:
    import: configserver:${CONFIG_SERVER_ADDRESS:http://172.20.1.1:10000}

logging:
  config: ${CONFIG_SERVER_ADDRESS:http://172.20.1.1:10000}/${spring.application.name}/${spring.profiles.active}/logback-spring.xml?useDefaultLabel=true&resolvePlaceholders=false
